services:
  redis:
    image: redis:7
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis:/data
    networks:
      - meteringBridge

  postgres:
    image: postgres:17
    container_name: local-postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./services/postgres:/var/lib/postgresql/data
    networks:
      - meteringBridge
  loki:
    container_name: loki
    image: grafana/loki:latest
    depends_on:
      - prometheus
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - meteringBridge
  prometheus:
    container_name: local-prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    depends_on:
      - redis
      - postgres
    networks:
      meteringBridge:
        aliases:
          - prometheus
  
  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    ports:
      - '8181:8181'
    volumes:
      - ./services/influxdb:/var/lib/influxdb3
    command: ["influxdb3", "serve", "--node-id=node0", "--object-store=file", "--data-dir=/var/lib/influxdb3"]
    depends_on:
      - redis
      - postgres
    networks:
      meteringBridge:
        aliases:
          - influxdb
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://local-loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        - name: InfluxDB
          type: influxdb
          access: proxy
          database: db0
          user: ${INFLUXDB_USERNAME}
          password: ${INFLUXDB_PASSWORD}
          token: ${INFLUXDB_TOKEN}
          url: http://influxdb:8181
          editable: true

          
        EOF
        /run.sh
    image: grafana/grafana:latest
    volumes:
      - ./services/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
      - influxdb
    networks:
      meteringBridge:
        aliases:
          - grafana

networks:
  meteringBridge:
    external: true
    
